CREATE TABLE smoke_test (id INTEGER, name VARCHAR)

INSERT INTO smoke_test VALUES (1, 'hello')

SELECT * FROM smoke_test

CREATE TABLE t (id INTEGER, name VARCHAR)

INSERT INTO t VALUES (1, 'alice'), (2, 'bob')

SELECT id, name FROM t ORDER BY id

CREATE TABLE nums (n INTEGER)

INSERT INTO nums VALUES (42)

SELECT n FROM nums

SELECT n FROM nums

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (1, 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE VIEW N_view AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0)

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS N_view CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP TABLE IF EXISTS N_g CASCADE

DROP INDEX IF EXISTS N_g___0

DROP INDEX IF EXISTS N_g___1

CREATE TABLE IF NOT EXISTS GENNEWID_MAP (
  NEWID BIGINT NOT NULL,
  VIEWRULEID VARCHAR(64) NOT NULL,
  INPUTS VARCHAR(256)
)

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO N_g VALUES (3, 'City')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

INSERT INTO E_g VALUES (11, 1, 3, 'LIVES_IN')

CREATE VIEW V_Person AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0 WHERE R0._1 = 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM V_Person AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Company')

CREATE TABLE MAT_Person AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0 WHERE R0._1 = 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM MAT_Person AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

((SELECT DISTINCT R0._0 AS _0, R1._2 AS _1 FROM N_g AS R0 CROSS JOIN E_g AS R1 CROSS JOIN N_g AS R2 WHERE R0._0 = R1._1 AND R1._2 = R2._0 AND R0._1 = 'Person' AND R1._3 = 'KNOWS' AND R2._1 = 'Person'))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO N_g VALUES (3, 'Person')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

((SELECT DISTINCT R0._0 AS _0 FROM N_g AS R0 LEFT JOIN E_g AS R1 ON R0._0=R1._1 WHERE R0._1 = 'Person' AND R1._1 IS NOT NULL))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (5, 'City')

((SELECT DISTINCT R0._0 AS _0, 'Place' AS _1 FROM N_g AS R0))

CREATE TABLE IF NOT EXISTS GENNEWID_MAP (
  NEWID BIGINT NOT NULL,
  VIEWRULEID VARCHAR(64) NOT NULL,
  INPUTS VARCHAR(256)
)

SELECT (CAST(hash('rule1' || '|' || CAST(42 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(42 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(1 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(2 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

CREATE TABLE t (id INTEGER, name VARCHAR)

INSERT INTO t VALUES (1, 'alice'), (2, 'bob')

SELECT id, name FROM t ORDER BY id

CREATE TABLE nums (n INTEGER)

INSERT INTO nums VALUES (42)

SELECT n FROM nums

SELECT n FROM nums

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (1, 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE VIEW N_view AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0)

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS N_view CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP TABLE IF EXISTS N_g CASCADE

DROP INDEX IF EXISTS N_g___0

DROP INDEX IF EXISTS N_g___1

CREATE TABLE IF NOT EXISTS GENNEWID_MAP (
  NEWID BIGINT NOT NULL,
  VIEWRULEID VARCHAR(64) NOT NULL,
  INPUTS VARCHAR(256)
)

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO N_g VALUES (3, 'City')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

INSERT INTO E_g VALUES (11, 1, 3, 'LIVES_IN')

CREATE VIEW V_Person AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0 WHERE R0._1 = 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM V_Person AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Company')

CREATE TABLE MAT_Person AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0 WHERE R0._1 = 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM MAT_Person AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

((SELECT DISTINCT R0._0 AS _0, R1._2 AS _1 FROM N_g AS R0 CROSS JOIN E_g AS R1 CROSS JOIN N_g AS R2 WHERE R0._0 = R1._1 AND R1._2 = R2._0 AND R0._1 = 'Person' AND R1._3 = 'KNOWS' AND R2._1 = 'Person'))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO N_g VALUES (3, 'Person')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

((SELECT DISTINCT R0._0 AS _0 FROM N_g AS R0 LEFT JOIN E_g AS R1 ON R0._0=R1._1 WHERE R0._1 = 'Person' AND R1._1 IS NULL))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (5, 'City')

((SELECT DISTINCT R0._0 AS _0, 'Place' AS _1 FROM N_g AS R0))

CREATE TABLE IF NOT EXISTS GENNEWID_MAP (
  NEWID BIGINT NOT NULL,
  VIEWRULEID VARCHAR(64) NOT NULL,
  INPUTS VARCHAR(256)
)

SELECT (CAST(hash('rule1' || '|' || CAST(42 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(42 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(1 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(2 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

CREATE TABLE t (id INTEGER, name VARCHAR)

INSERT INTO t VALUES (1, 'alice'), (2, 'bob')

SELECT id, name FROM t ORDER BY id

CREATE TABLE nums (n INTEGER)

INSERT INTO nums VALUES (42)

SELECT n FROM nums

SELECT n FROM nums

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (1, 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE VIEW N_view AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0)

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS N_view CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP VIEW IF EXISTS duckdb_columns CASCADE

DROP VIEW IF EXISTS duckdb_constraints CASCADE

DROP VIEW IF EXISTS duckdb_databases CASCADE

DROP VIEW IF EXISTS duckdb_indexes CASCADE

DROP VIEW IF EXISTS duckdb_schemas CASCADE

DROP VIEW IF EXISTS duckdb_tables CASCADE

DROP VIEW IF EXISTS duckdb_types CASCADE

DROP VIEW IF EXISTS duckdb_views CASCADE

DROP VIEW IF EXISTS pragma_database_list CASCADE

DROP VIEW IF EXISTS sqlite_master CASCADE

DROP VIEW IF EXISTS sqlite_schema CASCADE

DROP VIEW IF EXISTS sqlite_temp_master CASCADE

DROP VIEW IF EXISTS sqlite_temp_schema CASCADE

DROP TABLE IF EXISTS N_g CASCADE

DROP INDEX IF EXISTS N_g___0

DROP INDEX IF EXISTS N_g___1

CREATE TABLE IF NOT EXISTS GENNEWID_MAP (
  NEWID BIGINT NOT NULL,
  VIEWRULEID VARCHAR(64) NOT NULL,
  INPUTS VARCHAR(256)
)

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO N_g VALUES (3, 'City')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

INSERT INTO E_g VALUES (11, 1, 3, 'LIVES_IN')

CREATE VIEW V_Person AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0 WHERE R0._1 = 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM V_Person AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Company')

CREATE TABLE MAT_Person AS (SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM N_g AS R0 WHERE R0._1 = 'Person')

((SELECT DISTINCT R0._0 AS _0, R0._1 AS _1 FROM MAT_Person AS R0))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

((SELECT DISTINCT R0._0 AS _0, R1._2 AS _1 FROM N_g AS R0 CROSS JOIN E_g AS R1 CROSS JOIN N_g AS R2 WHERE R0._0 = R1._1 AND R1._2 = R2._0 AND R0._1 = 'Person' AND R1._3 = 'KNOWS' AND R2._1 = 'Person'))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

CREATE TABLE IF NOT EXISTS E_g (_0 INTEGER DEFAULT 0, _1 INTEGER DEFAULT 0, _2 INTEGER DEFAULT 0, _3 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS E_g___0 ON E_g (_0)

CREATE INDEX IF NOT EXISTS E_g___1 ON E_g (_1)

CREATE INDEX IF NOT EXISTS E_g___2 ON E_g (_2)

CREATE INDEX IF NOT EXISTS E_g___3 ON E_g (_3)

INSERT INTO N_g VALUES (1, 'Person')

INSERT INTO N_g VALUES (2, 'Person')

INSERT INTO N_g VALUES (3, 'Person')

INSERT INTO E_g VALUES (10, 1, 2, 'KNOWS')

((SELECT DISTINCT R0._0 AS _0 FROM N_g AS R0 LEFT JOIN E_g AS R1 ON R0._0=R1._1 WHERE R0._1 = 'Person' AND R1._1 IS NULL))

CREATE TABLE IF NOT EXISTS N_g (_0 INTEGER DEFAULT 0, _1 VARCHAR(1024))

CREATE INDEX IF NOT EXISTS N_g___0 ON N_g (_0)

CREATE INDEX IF NOT EXISTS N_g___1 ON N_g (_1)

INSERT INTO N_g VALUES (5, 'City')

((SELECT DISTINCT R0._0 AS _0, 'Place' AS _1 FROM N_g AS R0))

CREATE TABLE IF NOT EXISTS GENNEWID_MAP (
  NEWID BIGINT NOT NULL,
  VIEWRULEID VARCHAR(64) NOT NULL,
  INPUTS VARCHAR(256)
)

SELECT (CAST(hash('rule1' || '|' || CAST(42 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(42 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(1 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

SELECT (CAST(hash('rule1' || '|' || CAST(2 AS VARCHAR)) % 1900000000 AS BIGINT) + 100000000)

