[default]


[logicblox]
ip = 127.0.0.1
port = 5518
adminport = 5519
# lb_bin_dir should end with "/bin"
lb_bin_dir = ~/tools/logicblox/bin

[postgres]
ip = 127.0.0.1
port = 5432
username = postgres
password = postgres@ 
pg_dir = 

[neo4j]
# currently embedded=false is not supported
embedded = true
dbdir = neo4jdata
neo4j.dir = ~/tools/neo4j-community-4.1.11
# if embedded is true, below ip/port will be ignored
ip = 127.0.0.1
port = 7687

[duckdb]
# Directory where per-database .duckdb files are stored
dbdir = duckdbdata
